### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by OpticFusion1** [Royalphax/UltimateSheepWars#15]
**Is your feature request related to a problem? Please describe.**
"But I trust the plugin developers community and deeply hope that this plugin will be maintained."
There is currently no license, which makes this impossible to do given that the current license falls under "ALL RIGHTS RESERVED" meaning no one can do anything

**Describe the solution you'd like**
A proper open source license should be added to the repository, e.g. GPLv3 or MIT. Without a proper license, there is not much we can do with this source code when it comes to properly maintaining the resource

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Royalphax** [comment]
Done 👍🏻 
Thanks!
