### ISSUE TITLE
[Bug] Mouton Soigneur

### ISSUE THREAD

**Issue by Luray98** [Royalphax/UltimateSheepWars#18]
Bonjour, il y a un bug avec le mouton soigneur il passe à travers les blocks.

Pourriez vous régler ce problème ? J'ai constater ce bug sur des demies dalles je n'ai pas tester sur des blocks plein mais je crois que cela fait la même chose.

Le problème est en 1.8.8 avec la dernière version du plugin.

Merci d'avance.

**Comment by Royalphax** [comment]
Bonjour problème réglé (déjà mentionné) et corrigé dans le code. J'ai hâte de pouvoir publier la MAJ du plugin pour que vous puissiez voir par vous même ;)

Merci pour votre report en tous cas !
