### ISSUE TITLE
[Amélioration] Mouton d'Abordage

### ISSUE THREAD

**Issue by Luray98** [Royalphax/UltimateSheepWars#19]
Bonjour, le Mouton d'Abordage est mal fait à mon goût. Il est très bugé. Il faudrait déjà que quand le mouton touche le sol il disparaisse. Je pense que vous pourriez l'améliorer.

Merci d'avance

**Comment by Royalphax** [comment]
En effet, vous avez dû voir qu'il semble vous "téléporter" toutes les x secondes. C'est très désagréable ! Encore une fois, c'est un bug majeur que j'ai déjà réglé aussi.

Au plaisir de vous partager la nouvelle version du plugin pour que vous puissiez tester par vous même et me faire votre retour. Bonne soirée !
